### ISSUE TITLE
Marketing meta details

### ISSUE THREAD

**Issue by WalterBanda** [WalterBanda/chapchap-client#26]
- [ ] Add Marketing meta details
- [ ] Marketing meta image
- [ ] Layoutfix - fix button and input sizing in web
