### ISSUE TITLE
Release workflow: Build a release workflow for Github releases with screenshots of changes

### ISSUE THREAD

**Issue by WalterBanda** [WalterBanda/chapchap-client#31]
- [x] Locking of Flutter SDK to reduce artifacts and deprications
- [x] Creating container caches for flutter sdk and project dependacies
- [x] Refactoring firebase deployment to reuse cache and containers
- [x] Building github release workflows for android, linux, windows.
- [x] Building auto release notes and screenshots using fastlane for android.
- [x] Building release template for playstore

**Comment by WalterBanda** [comment]
Written all workflows for the repository
